### ISSUE TITLE
Error installing ...

### ISSUE THREAD

**Issue by ReneBakkerBBIT** [jumbaeric/docverter#1]
On: composer require jumbaeric/Docverter

Composer says:

 Could not find a matching version of package jumbaeric/Docverter. Check the package spelling, your version constraint and that
  the package is available in a stability which matches your minimum-stability (dev).

Now what?

**Comment by trentmu** [comment]
I had a similar output/result - debian buster with PHP 7.4.x
I tried changing the .json to `minimum-stability:dev` but the problem still there

**Comment by jumbaeric** [comment]
this is fixed. try again

**Comment by trentmu** [comment]
Worked perfectly - thank you Eric!!
I have now updated to bullseye and all still seems OK

**Comment by jumbaeric** [comment]
Awesome. Happy coding.
